CREATE OR REPLACE STAGE SIM_BOM.MASTER_DATA.CSV_STAGE;
PUT file:///home/ubuntu/INTEL_ASSESMENT_2/CSV_files/Item_master.csv @SIM_BOM.MASTER_DATA.CSV_STAGE;

PUT file:///home/ubuntu/INTEL_ASSESMENT_2/CSV_files/Location_master.csv @SIM_BOM.MASTER_DATA.CSV_STAGE;

PUT file:///home/ubuntu/INTEL_ASSESMENT_2/CSV_files/ORIG_BOM_MASTER.csv @SIM_BOM.MASTER_DATA.CSV_STAGE;

CREATE OR REPLACE FILE FORMAT CSV_FILE_FORMAT
TYPE = 'CSV'
FIELD_OPTIONALLY_ENCLOSED_BY = '"'
SKIP_HEADER = 1;

COPY INTO SIM_BOM.MASTER_DATA.ITEM
FROM @SIM_BOM.MASTER_DATA.CSV_STAGE/Item_master.csv
FILE_FORMAT = (FORMAT_NAME = 'CSV_FILE_FORMAT', TYPE = CSV);

COPY INTO SIM_BOM.MASTER_DATA.LOCATION
FROM @SIM_BOM.MASTER_DATA.CSV_STAGE/Location_master.csv
FILE_FORMAT = (FORMAT_NAME = 'CSV_FILE_FORMAT', TYPE = CSV,SKIP_HEADER=1);

COPY INTO SIM_BOM.MASTER_DATA.ORIG_BOM
FROM @SIM_BOM.MASTER_DATA.CSV_STAGE/ORIG_BOM_MASTER.csv
FILE_FORMAT = (FORMAT_NAME = 'CSV_FILE_FORMAT', TYPE = CSV,SKIP_HEADER=1);
