CREATE OR REPLACE PROCEDURE SIM_BOM.BMATHUB_BASE.P_UPDATE_LOC()
  RETURNS VARCHAR
  LANGUAGE SQL
  AS
  $$
  BEGIN
     
     UPDATE SIM_BOM.BMATHUB_BASE.T_ORIG_BOM ORG
     SET ORG.LOCATION_ID = LOCATION.LOCATION_ID 
     FROM SIM_BOM.BMATHUB_BASE.T_ITEM_DETAIL_ROOT ITEM
     JOIN SIM_BOM.BMATHUB_BASE.T_ITEM_LOCATION_ROOT LOCATION ON ITEM.ITEM_ID = LOCATION.ITEM_ID
     WHERE ORG.INPUT_ITEM_ID = ITEM.ITEM_ID;
     
     RETURN 'Update operation completed successfully';
  END;
  $$
  ;


CALL SIM_BOM.BMATHUB_BASE.P_UPDATE_LOC();
