-- CREATE VIEW SIM_BOM.BMATHUB_BASE.V_COMPRESS_BOM AS
-- SELECT INPUT_ITEM_ID,
--        ITEM_CLASS_NM,
--        ANCHOR_ITEM_ID,
--        BOM_NUM,
--        LOCATION_ID,
--        CREATE_DTM,
--        CREATE_USER
-- FROM SIM_BOM.BMATHUB_BASE.T_COMPRESS_BOM;


CREATE OR REPLACE VIEW SIM_BOM.BMATHUB_BASE.COMPRESSED_BOM_VIEW AS
SELECT 
    ic.INPUT_ITEM_ID AS ITEM,  -- The final IC item
    ic.ITEM_CLASS_NM AS ITEM_CLASS_NM,  -- The class for IC
    sort.INPUT_ITEM_ID AS ANCHOR_ITEM_ID,  -- The initial UPI_SORT item
    ic.BOM_NUM,  -- BOM Number from IC
    ic.LOC  -- Location from IC
FROM SIM_BOM.BMATHUB_BASE.T_COMPRESS_BOM_CORE ic
JOIN SIM_BOM.BMATHUB_BASE.T_COMPRESS_BOM_CORE dieprep
    ON ic.INPUT_ITEM_ID = dieprep.OUTPUT_ITEM_ID
    AND dieprep.ITEM_CLASS_NM = 'UPI_DIEPREP'
JOIN SIM_BOM.BMATHUB_BASE.T_COMPRESS_BOM_CORE sort
    ON dieprep.INPUT_ITEM_ID = sort.OUTPUT_ITEM_ID
    AND sort.ITEM_CLASS_NM = 'UPI_SORT'
WHERE ic.ITEM_CLASS_NM = 'IC';
