
CREATE OR REPLACE VIEW SIM_BOM.BMATHUB_ANALYSIS.SIM_BOM AS
select ITEM,ITEM_CLASS_NM,ANCHOR_ITEM_ID,BOM_NUM,LOCATION_ID AS LOC ,'64 BIT CHIPSET' as DESCRIP
FROM 
SIM_BOM.BMATHUB_BASE.COMPRESSED_BOM_VIEW ;