
CREATE TABLE SIM_BOM.BMATHUB_BASE.T_COMPRESS_BOM (
    INPUT_ITEM_ID VARCHAR(21),
    ITEM_CLASS_NM VARCHAR(21),
    OUTPUT_ITEM_ID VARCHAR(21),
    BOM_NUM INTEGER,
    LOCATION_ID VARCHAR(10)
    );
